# Tom Trebisky  4-25-2020

setup:
	npm init -y
	npm install --save express
	npm install --save express-handlebars
	npm install --save body-parser

run:
	node form.js

clean:
	rm -rf node_modules
	rm -f package.json
	rm -f package-lock.json
